const fs = require('fs');
const path = require('path');

function mergeEnv(sourcePath, targetPath) {
  if (!fs.existsSync(sourcePath)) return;
  console.log(`Processing ${sourcePath} -> ${targetPath}`);

  const sourceContent = fs.readFileSync(sourcePath, 'utf8');
  const targetContent = fs.existsSync(targetPath) ? fs.readFileSync(targetPath, 'utf8') : '';

  const deploymentMatch = sourceContent.match(/CONVEX_DEPLOYMENT=(.+)/);
  const urlMatch = sourceContent.match(/NEXT_PUBLIC_CONVEX_URL=(.+)/) || sourceContent.match(/EXPO_PUBLIC_CONVEX_URL=(.+)/);

  if (deploymentMatch && urlMatch) {
    console.log(`Found config: ${deploymentMatch[1]}`);
    
    let newContent = targetContent;
    
    // Replace or Append CONVEX_DEPLOYMENT
    const deploymentValue = deploymentMatch[1].split('#')[0].trim();

    if (newContent.includes('CONVEX_DEPLOYMENT=')) {
      newContent = newContent.replace(/CONVEX_DEPLOYMENT=.*/, `CONVEX_DEPLOYMENT=${deploymentValue}`);
    } else {
      newContent += `\nCONVEX_DEPLOYMENT=${deploymentValue}`;
    }

    // Replace or Append URL
    // For root (Expo), it's EXPO_PUBLIC_CONVEX_URL
    // For web (Next), it's NEXT_PUBLIC_CONVEX_URL
    const isWeb = targetPath.includes('web');
    const urlVar = isWeb ? 'NEXT_PUBLIC_CONVEX_URL' : 'EXPO_PUBLIC_CONVEX_URL';
    const sourceUrl = urlMatch[1].split('#')[0].trim();

    if (newContent.includes(`${urlVar}=`)) {
      newContent = newContent.replace(new RegExp(`${urlVar}=.*`), `${urlVar}=${sourceUrl}`);
    } else {
      newContent += `\n${urlVar}=${sourceUrl}`;
    }

    fs.writeFileSync(targetPath, newContent);
    console.log(`✅ Updated ${targetPath}`);
    
    // Rename source to avoid confusion? No, keep it as backup or delete it?
    // Convex will keep recreating it.
    // Ideally we tell Convex to use the .env.development file? No, it defaults to .env.local
  }
}

// Check Root
// generated by `npx convex dev` in root -> usually .env.local
mergeEnv('.env.local', '.env.development');

// Check Web
// generated by `npx convex dev` if run in web -> web/.env.local
mergeEnv('web/.env.local', 'web/.env.development.local');

console.log("Done! If you just ran 'npx convex dev', your development files should now be ready.");
